name = "lustre_http"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.68"
gleam_json = "~> 3.0"
gleam_http = "~> 4.3"
gleam_fetch = "~> 1.3"
gleam_javascript = "~> 1.0"
lustre = "~> 5.0"

[dev-dependencies]
gleeunit = "~> 1.0"
