name = "scrumbringer_server"
version = "0.1.0"
target = "erlang"

description = "ScrumBringer HTTP API server"
licences = ["Apache-2.0"]

[dependencies]
# Note: Use `.tools/gleam-1.14.0/gleam` for this repo.
gleam_stdlib = "0.68.1"
gleam_erlang = "1.3.0"
# HTTP
wisp = "2.1.1"
gleam_http = "4.3.0"
gleam_json = "3.1.0"
gleam_otp = "1.2.0"
mist = "5.0.4"
# Crypto
# NOTE: Argon2 implementation is provided via an Erlang dependency in src/services/password.gleam.
gleam_crypto = "~> 1.0"
scrumbringer_domain = { path = "../../packages/domain" }
shared = { path = "../../shared" }
argon2 = ">= 1.2.0 and < 2.0.0"
birl = { path = "../../packages/birl" }
# DB
pog = "~> 4.0"

[dev-dependencies]
gleeunit = "~> 1.0"
squirrel = "~> 4.0"
